<a href="https://colab.research.google.com/github/RafaBessa/Learning_NeuralNets/blob/master/KNN_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import sklearn


In [25]:
#Load DATA
iris = load_iris()
x = iris['data']
y = iris['target']
#print(x)
print(iris['target_names'])


['setosa' 'versicolor' 'virginica']


In [0]:
#aproximando os valores, para uma maior precisao
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)


scaler = MinMaxScaler()
#print(iris['data'])
x_train=scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [32]:
#Criando o classifier e o trainando para o dataset
#Prevendo os valores do test
#guia das metricas https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html
classifier = KNeighborsClassifier(n_neighbors=5)
#print(classifier)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

[0 0 0 1 2 1 2 1 1 0 1 2 1 1 2 1 0 2 2 2 0 1 1 1 0 2 2 0 1 0]
[0 0 0 1 2 1 2 1 1 0 1 2 1 1 2 1 0 1 2 2 0 1 1 1 0 2 2 0 1 0]


In [36]:
#availiando o metodo
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 9  0  0]
 [ 0 12  1]
 [ 0  3  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.80      0.92      0.86        13
           2       0.83      0.62      0.71         8

    accuracy                           0.87        30
   macro avg       0.88      0.85      0.86        30
weighted avg       0.87      0.87      0.86        30



In [37]:
#mahalanobis
#guia das metricas https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html

classifier = KNeighborsClassifier(n_neighbors=5,metric = 'mahalanobis', metric_params={'V': np.cov(x_train,rowvar=False)})
#print(classifier)                                                                                covariance matrix
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print(y_pred)
print(y_test)

[0 0 0 2 2 1 1 1 1 0 1 1 1 1 2 1 0 1 1 2 0 1 1 1 0 2 2 0 1 0]
[0 0 0 1 2 1 2 1 1 0 1 2 1 1 2 1 0 1 2 2 0 1 1 1 0 2 2 0 1 0]


In [38]:
#availiando o metodo

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 9  0  0]
 [ 0 12  1]
 [ 0  3  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.80      0.92      0.86        13
           2       0.83      0.62      0.71         8

    accuracy                           0.87        30
   macro avg       0.88      0.85      0.86        30
weighted avg       0.87      0.87      0.86        30

